### ISSUE TITLE
Could not load template, failed with: Syntax error macroexpanding clojure.core/fn at (clojure/core/unify.clj:83:18)

### ISSUE THREAD

**Issue by teogenesmoura** [yogthos/compojure-template#8]
Hi guys, how are you?
I'm trying to create a new app with the compojure-app template but I'm getting this error message in the terminal:

`Could not load template, failed with: Syntax error macroexpanding clojure.core/fn at (clojure/core/unify.clj:83:18)`

The command I'm running is 

`lein new compojure-app myapp`

Is anyone else facing the same issue?

**Comment by yogthos** [comment]
Hi,

It looks like the template had some old dependencies that no longer work. I just pushed out an updated version that should fix the issue. Let me know if it looks good on your end.
